name: Deploy to Heroku

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku Container Registry
        run: docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
        env:
          HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}}
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

      - name: Build and Push Docker Images
        run: |
          docker build -t registry.heroku.com/your-app-name/web webApp/
          docker push registry.heroku.com/your-app-name/web
          
          docker build -t registry.heroku.com/your-app-name/datacollector DataCollector/
          docker push registry.heroku.com/your-app-name/datacollector

      - name: Release Images to Heroku
        run: |
          heroku container:release web datacollector -a your-app-name
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

